### ISSUE TITLE
Automatically filter /appmetrics-dash

### ISSUE THREAD

**Issue by cfjedimaster** [RuntimeTools/appmetrics-dash#78]
I just started up my server and the first thing I hit was my dashboard. The Average Response time chart is showing multiple requests related to /appmetrics-dash. These should be ignored by default (and obviously, if I were to switch the path to something else, it should filter that path). I know (or am pretty sure) I can set this as an option, but it should be there by default.

**Comment by cfjedimaster** [comment]
You know - now that I think of it - I do think you have a point. If the server is - well - serving it - then maybe it should be reported. I'm happy to close this, but maybe we can let someone else chime in as well. :)

**Comment by tobespc** [comment]
@cfjedimaster We have gone back and forth on this as well as to whether to show this data.  We are looking at redesigning some of the graphs and adding new options/config that would assist in this.  Things like highlighting similar requests etc and so showing which calls were made by appmetrics-dash would be colour coded

**Comment by hhellyer** [comment]
I think there's a fairly strong case for hiding these from the top 5 as it stands. All we show at the moment is the top 5 highest mean response times. As typically the `/appmetrics-dash` urls are only requested once (or rarely) that gives terrible average response times as they include disk reads that aren't averaged out by having more than one request. In my test environment they end up occupying the top 5 forever. (If you repeatedly load `/appmetrics-dash` the average response times for paths under `/appmetrics-dash` drop rapidly.) Also it's unlikely the user wants to know about our monitoring tool rather than their application.

In the longer term I'll raise a graphmetrics issue to make the top 5 more useful so you can choose to see the average response times, the average response times of the 5 most requested urls, the 5 slowest urls or the 5 urls with the highest total request time overall. All of those are useful depending on what you are trying to understand about your application.  (We may need to add an option here too to show the dashboard paths in case we do cause a problem.)

**Comment by hhellyer** [comment]
I've raised the graphmetrics issue here:
https://github.com/RuntimeTools/graphmetrics/issues/33

**Comment by sjanuary** [comment]
Now filtering
